# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17 for compile
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          check-latest: false
      - name: Compile
        run: mvn clean package -P CI --batch-mode --quiet
      - name: Benchmark
        run: mvn compile exec:java
    
